//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 02:06:11 PM CET 
//


package org.openntf.base.jaxb.dxl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for actionbar.background.repeats.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="actionbar.background.repeats">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="once"/>
 *     &lt;enumeration value="vrepeat"/>
 *     &lt;enumeration value="hrepeat"/>
 *     &lt;enumeration value="tile"/>
 *     &lt;enumeration value="centertile"/>
 *     &lt;enumeration value="resize"/>
 *     &lt;enumeration value="center"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "actionbar.background.repeats", namespace = "http://www.lotus.com/dxl")
@XmlEnum
public enum ActionbarBackgroundRepeats {

    @XmlEnumValue("once")
    ONCE("once"),
    @XmlEnumValue("vrepeat")
    VREPEAT("vrepeat"),
    @XmlEnumValue("hrepeat")
    HREPEAT("hrepeat"),
    @XmlEnumValue("tile")
    TILE("tile"),
    @XmlEnumValue("centertile")
    CENTERTILE("centertile"),
    @XmlEnumValue("resize")
    RESIZE("resize"),
    @XmlEnumValue("center")
    CENTER("center");
    private final String value;

    ActionbarBackgroundRepeats(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ActionbarBackgroundRepeats fromValue(String v) {
        for (ActionbarBackgroundRepeats c: ActionbarBackgroundRepeats.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
