//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 02:06:11 PM CET 
//


package org.openntf.base.jaxb.dxl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for actionbutton.displayborder.types.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="actionbutton.displayborder.types">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="onmouseover"/>
 *     &lt;enumeration value="always"/>
 *     &lt;enumeration value="never"/>
 *     &lt;enumeration value="notesstyle"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "actionbutton.displayborder.types", namespace = "http://www.lotus.com/dxl")
@XmlEnum
public enum ActionbuttonDisplayborderTypes {

    @XmlEnumValue("onmouseover")
    ONMOUSEOVER("onmouseover"),
    @XmlEnumValue("always")
    ALWAYS("always"),
    @XmlEnumValue("never")
    NEVER("never"),
    @XmlEnumValue("notesstyle")
    NOTESSTYLE("notesstyle");
    private final String value;

    ActionbuttonDisplayborderTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ActionbuttonDisplayborderTypes fromValue(String v) {
        for (ActionbuttonDisplayborderTypes c: ActionbuttonDisplayborderTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
