//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 02:06:11 PM CET 
//


package org.openntf.base.jaxb.dxl;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for area complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="area">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;sequence>
 *             &lt;element name="point" type="{http://www.lotus.com/dxl}point" maxOccurs="unbounded" minOccurs="2"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="doclink" type="{http://www.lotus.com/dxl}doclink"/>
 *           &lt;element name="viewlink" type="{http://www.lotus.com/dxl}viewlink"/>
 *           &lt;element name="databaselink" type="{http://www.lotus.com/dxl}databaselink"/>
 *           &lt;element name="urllink" type="{http://www.lotus.com/dxl}urllink"/>
 *           &lt;element name="namedelementlink" type="{http://www.lotus.com/dxl}namedelementlink"/>
 *         &lt;/choice>
 *         &lt;element name="code" type="{http://www.lotus.com/dxl}code" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.lotus.com/dxl}html.core.attrs"/>
 *       &lt;attribute name="type" type="{http://www.lotus.com/dxl}area.type" />
 *       &lt;attribute name="tabindex" type="{http://www.w3.org/2001/XMLSchema}integer" default="0" />
 *       &lt;attribute name="alttext" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="targetframe" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "area", namespace = "http://www.lotus.com/dxl", propOrder = {
    "point",
    "doclink",
    "viewlink",
    "databaselink",
    "urllink",
    "namedelementlink",
    "code"
})
public class Area {

    protected List<Point> point;
    protected Doclink doclink;
    protected Viewlink viewlink;
    protected Databaselink databaselink;
    protected Urllink urllink;
    protected Namedelementlink namedelementlink;
    protected List<Code> code;
    @XmlAttribute
    protected AreaType type;
    @XmlAttribute
    protected BigInteger tabindex;
    @XmlAttribute
    protected String alttext;
    @XmlAttribute
    protected String targetframe;
    @XmlAttribute
    protected String htmlid;
    @XmlAttribute
    protected String htmlclass;
    @XmlAttribute
    protected String htmlstyle;
    @XmlAttribute
    protected String htmltitle;
    @XmlAttribute
    protected String extrahtmlattrs;

    /**
     * Gets the value of the point property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the point property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Point }
     * 
     * 
     */
    public List<Point> getPoint() {
        if (point == null) {
            point = new ArrayList<Point>();
        }
        return this.point;
    }

    /**
     * Gets the value of the doclink property.
     * 
     * @return
     *     possible object is
     *     {@link Doclink }
     *     
     */
    public Doclink getDoclink() {
        return doclink;
    }

    /**
     * Sets the value of the doclink property.
     * 
     * @param value
     *     allowed object is
     *     {@link Doclink }
     *     
     */
    public void setDoclink(Doclink value) {
        this.doclink = value;
    }

    /**
     * Gets the value of the viewlink property.
     * 
     * @return
     *     possible object is
     *     {@link Viewlink }
     *     
     */
    public Viewlink getViewlink() {
        return viewlink;
    }

    /**
     * Sets the value of the viewlink property.
     * 
     * @param value
     *     allowed object is
     *     {@link Viewlink }
     *     
     */
    public void setViewlink(Viewlink value) {
        this.viewlink = value;
    }

    /**
     * Gets the value of the databaselink property.
     * 
     * @return
     *     possible object is
     *     {@link Databaselink }
     *     
     */
    public Databaselink getDatabaselink() {
        return databaselink;
    }

    /**
     * Sets the value of the databaselink property.
     * 
     * @param value
     *     allowed object is
     *     {@link Databaselink }
     *     
     */
    public void setDatabaselink(Databaselink value) {
        this.databaselink = value;
    }

    /**
     * Gets the value of the urllink property.
     * 
     * @return
     *     possible object is
     *     {@link Urllink }
     *     
     */
    public Urllink getUrllink() {
        return urllink;
    }

    /**
     * Sets the value of the urllink property.
     * 
     * @param value
     *     allowed object is
     *     {@link Urllink }
     *     
     */
    public void setUrllink(Urllink value) {
        this.urllink = value;
    }

    /**
     * Gets the value of the namedelementlink property.
     * 
     * @return
     *     possible object is
     *     {@link Namedelementlink }
     *     
     */
    public Namedelementlink getNamedelementlink() {
        return namedelementlink;
    }

    /**
     * Sets the value of the namedelementlink property.
     * 
     * @param value
     *     allowed object is
     *     {@link Namedelementlink }
     *     
     */
    public void setNamedelementlink(Namedelementlink value) {
        this.namedelementlink = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the code property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Code }
     * 
     * 
     */
    public List<Code> getCode() {
        if (code == null) {
            code = new ArrayList<Code>();
        }
        return this.code;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link AreaType }
     *     
     */
    public AreaType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link AreaType }
     *     
     */
    public void setType(AreaType value) {
        this.type = value;
    }

    /**
     * Gets the value of the tabindex property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTabindex() {
        if (tabindex == null) {
            return new BigInteger("0");
        } else {
            return tabindex;
        }
    }

    /**
     * Sets the value of the tabindex property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTabindex(BigInteger value) {
        this.tabindex = value;
    }

    /**
     * Gets the value of the alttext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlttext() {
        return alttext;
    }

    /**
     * Sets the value of the alttext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlttext(String value) {
        this.alttext = value;
    }

    /**
     * Gets the value of the targetframe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetframe() {
        return targetframe;
    }

    /**
     * Sets the value of the targetframe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetframe(String value) {
        this.targetframe = value;
    }

    /**
     * Gets the value of the htmlid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHtmlid() {
        return htmlid;
    }

    /**
     * Sets the value of the htmlid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHtmlid(String value) {
        this.htmlid = value;
    }

    /**
     * Gets the value of the htmlclass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHtmlclass() {
        return htmlclass;
    }

    /**
     * Sets the value of the htmlclass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHtmlclass(String value) {
        this.htmlclass = value;
    }

    /**
     * Gets the value of the htmlstyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHtmlstyle() {
        return htmlstyle;
    }

    /**
     * Sets the value of the htmlstyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHtmlstyle(String value) {
        this.htmlstyle = value;
    }

    /**
     * Gets the value of the htmltitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHtmltitle() {
        return htmltitle;
    }

    /**
     * Sets the value of the htmltitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHtmltitle(String value) {
        this.htmltitle = value;
    }

    /**
     * Gets the value of the extrahtmlattrs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtrahtmlattrs() {
        return extrahtmlattrs;
    }

    /**
     * Sets the value of the extrahtmlattrs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtrahtmlattrs(String value) {
        this.extrahtmlattrs = value;
    }

}
