//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 02:06:11 PM CET 
//


package org.openntf.base.jaxb.dxl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for border complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="border">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="imageref" type="{http://www.lotus.com/dxl}imageref" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="style" type="{http://www.lotus.com/dxl}border.styles" default="none" />
 *       &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}string" default="0" />
 *       &lt;attribute name="insidewidth" type="{http://www.w3.org/2001/XMLSchema}string" default="0" />
 *       &lt;attribute name="outsidewidth" type="{http://www.w3.org/2001/XMLSchema}string" default="0" />
 *       &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}string" default="black" />
 *       &lt;attribute name="dropshadow" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="dropshadowwidth" type="{http://www.w3.org/2001/XMLSchema}string" default="12px" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "border", namespace = "http://www.lotus.com/dxl", propOrder = {
    "imageref"
})
public class Border {

    protected Imageref imageref;
    @XmlAttribute
    protected BorderStyles style;
    @XmlAttribute
    protected String width;
    @XmlAttribute
    protected String insidewidth;
    @XmlAttribute
    protected String outsidewidth;
    @XmlAttribute
    protected String color;
    @XmlAttribute
    protected Boolean dropshadow;
    @XmlAttribute
    protected String dropshadowwidth;

    /**
     * Gets the value of the imageref property.
     * 
     * @return
     *     possible object is
     *     {@link Imageref }
     *     
     */
    public Imageref getImageref() {
        return imageref;
    }

    /**
     * Sets the value of the imageref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Imageref }
     *     
     */
    public void setImageref(Imageref value) {
        this.imageref = value;
    }

    /**
     * Gets the value of the style property.
     * 
     * @return
     *     possible object is
     *     {@link BorderStyles }
     *     
     */
    public BorderStyles getStyle() {
        if (style == null) {
            return BorderStyles.NONE;
        } else {
            return style;
        }
    }

    /**
     * Sets the value of the style property.
     * 
     * @param value
     *     allowed object is
     *     {@link BorderStyles }
     *     
     */
    public void setStyle(BorderStyles value) {
        this.style = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidth() {
        if (width == null) {
            return "0";
        } else {
            return width;
        }
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidth(String value) {
        this.width = value;
    }

    /**
     * Gets the value of the insidewidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsidewidth() {
        if (insidewidth == null) {
            return "0";
        } else {
            return insidewidth;
        }
    }

    /**
     * Sets the value of the insidewidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsidewidth(String value) {
        this.insidewidth = value;
    }

    /**
     * Gets the value of the outsidewidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutsidewidth() {
        if (outsidewidth == null) {
            return "0";
        } else {
            return outsidewidth;
        }
    }

    /**
     * Sets the value of the outsidewidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutsidewidth(String value) {
        this.outsidewidth = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColor() {
        if (color == null) {
            return "black";
        } else {
            return color;
        }
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColor(String value) {
        this.color = value;
    }

    /**
     * Gets the value of the dropshadow property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isDropshadow() {
        if (dropshadow == null) {
            return false;
        } else {
            return dropshadow;
        }
    }

    /**
     * Sets the value of the dropshadow property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDropshadow(Boolean value) {
        this.dropshadow = value;
    }

    /**
     * Gets the value of the dropshadowwidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDropshadowwidth() {
        if (dropshadowwidth == null) {
            return "12px";
        } else {
            return dropshadowwidth;
        }
    }

    /**
     * Sets the value of the dropshadowwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDropshadowwidth(String value) {
        this.dropshadowwidth = value;
    }

}
