//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 02:06:11 PM CET 
//


package org.openntf.base.jaxb.dxl;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for column complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="column">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="font" type="{http://www.lotus.com/dxl}font" minOccurs="0"/>
 *         &lt;element name="columnheader" type="{http://www.lotus.com/dxl}columnheader" minOccurs="0"/>
 *         &lt;element name="datetimeformat" type="{http://www.lotus.com/dxl}datetimeformat" minOccurs="0"/>
 *         &lt;element name="numberformat" type="{http://www.lotus.com/dxl}numberformat" minOccurs="0"/>
 *         &lt;element name="columnnamesformat" type="{http://www.lotus.com/dxl}columnnamesformat" minOccurs="0"/>
 *         &lt;element name="code" type="{http://www.lotus.com/dxl}code" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="twistieimage" type="{http://www.lotus.com/dxl}twistieimage" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.lotus.com/dxl}reading.order.attrs"/>
 *       &lt;attribute name="align" type="{http://www.lotus.com/dxl}simple.aligns" default="left" />
 *       &lt;attribute name="showasicons" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="resizable" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="responsesonly" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="hidden" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="editable" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="twisties" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="sort" type="{http://www.lotus.com/dxl}sort.orders" />
 *       &lt;attribute name="sortnocase" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="sortnoaccent" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="separatemultiplevalues" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="categorized" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="resort" type="{http://www.lotus.com/dxl}resort.options" />
 *       &lt;attribute name="resorttoview" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="resort2" type="{http://www.lotus.com/dxl}sort.orders" />
 *       &lt;attribute name="resort2column" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="totals" type="{http://www.lotus.com/dxl}totals.options" />
 *       &lt;attribute name="hidedetailrows" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="showaslinks" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="itemname" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="listseparator" type="{http://www.lotus.com/dxl}list.separators" />
 *       &lt;attribute name="flatinr5" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="showascolor" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="userdefinable" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="profiledocname" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="usecolumnformula" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="hidecolumntitle" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="hideinr5" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="deferindexcreation" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="extwindowwidth" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="justifysecondrow" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="viewisnarrow" type="{http://www.lotus.com/dxl}narrow.options" default="top" />
 *       &lt;attribute name="sequence" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="tileviewer" type="{http://www.lotus.com/dxl}tileviewer.options" default="top" />
 *       &lt;attribute name="linenumber" type="{http://www.w3.org/2001/XMLSchema}integer" default="1" />
 *       &lt;attribute name="extattrs" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="publish" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="formatdatatype" type="{http://www.lotus.com/dxl}columnformat.datatypes" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "column", namespace = "http://www.lotus.com/dxl", propOrder = {
    "font",
    "columnheader",
    "datetimeformat",
    "numberformat",
    "columnnamesformat",
    "code",
    "twistieimage"
})
public class Column {

    protected Font font;
    protected Columnheader columnheader;
    protected Datetimeformat datetimeformat;
    protected Numberformat numberformat;
    protected Columnnamesformat columnnamesformat;
    protected List<Code> code;
    protected Twistieimage twistieimage;
    @XmlAttribute
    protected SimpleAligns align;
    @XmlAttribute
    protected Boolean showasicons;
    @XmlAttribute
    protected Boolean resizable;
    @XmlAttribute
    protected Boolean responsesonly;
    @XmlAttribute
    protected Boolean hidden;
    @XmlAttribute
    protected Boolean editable;
    @XmlAttribute
    protected Boolean twisties;
    @XmlAttribute
    protected SortOrders sort;
    @XmlAttribute
    protected Boolean sortnocase;
    @XmlAttribute
    protected Boolean sortnoaccent;
    @XmlAttribute
    protected Boolean separatemultiplevalues;
    @XmlAttribute
    protected Boolean categorized;
    @XmlAttribute
    protected ResortOptions resort;
    @XmlAttribute
    protected String resorttoview;
    @XmlAttribute
    protected SortOrders resort2;
    @XmlAttribute(name = "resort2column")
    protected BigInteger resort2Column;
    @XmlAttribute
    protected TotalsOptions totals;
    @XmlAttribute
    protected Boolean hidedetailrows;
    @XmlAttribute
    protected Boolean showaslinks;
    @XmlAttribute
    protected String itemname;
    @XmlAttribute
    protected Float width;
    @XmlAttribute
    protected ListSeparators listseparator;
    @XmlAttribute
    protected Boolean flatinr5;
    @XmlAttribute
    protected Boolean showascolor;
    @XmlAttribute
    protected Boolean userdefinable;
    @XmlAttribute
    protected String profiledocname;
    @XmlAttribute
    protected Boolean usecolumnformula;
    @XmlAttribute
    protected Boolean hidecolumntitle;
    @XmlAttribute
    protected Boolean hideinr5;
    @XmlAttribute
    protected Boolean deferindexcreation;
    @XmlAttribute
    protected Boolean extwindowwidth;
    @XmlAttribute
    protected Boolean justifysecondrow;
    @XmlAttribute
    protected NarrowOptions viewisnarrow;
    @XmlAttribute
    protected BigInteger sequence;
    @XmlAttribute
    protected TileviewerOptions tileviewer;
    @XmlAttribute
    protected BigInteger linenumber;
    @XmlAttribute
    protected String extattrs;
    @XmlAttribute
    protected String publish;
    @XmlAttribute
    protected ColumnformatDatatypes formatdatatype;
    @XmlAttribute
    protected String readingorder;

    /**
     * Gets the value of the font property.
     * 
     * @return
     *     possible object is
     *     {@link Font }
     *     
     */
    public Font getFont() {
        return font;
    }

    /**
     * Sets the value of the font property.
     * 
     * @param value
     *     allowed object is
     *     {@link Font }
     *     
     */
    public void setFont(Font value) {
        this.font = value;
    }

    /**
     * Gets the value of the columnheader property.
     * 
     * @return
     *     possible object is
     *     {@link Columnheader }
     *     
     */
    public Columnheader getColumnheader() {
        return columnheader;
    }

    /**
     * Sets the value of the columnheader property.
     * 
     * @param value
     *     allowed object is
     *     {@link Columnheader }
     *     
     */
    public void setColumnheader(Columnheader value) {
        this.columnheader = value;
    }

    /**
     * Gets the value of the datetimeformat property.
     * 
     * @return
     *     possible object is
     *     {@link Datetimeformat }
     *     
     */
    public Datetimeformat getDatetimeformat() {
        return datetimeformat;
    }

    /**
     * Sets the value of the datetimeformat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Datetimeformat }
     *     
     */
    public void setDatetimeformat(Datetimeformat value) {
        this.datetimeformat = value;
    }

    /**
     * Gets the value of the numberformat property.
     * 
     * @return
     *     possible object is
     *     {@link Numberformat }
     *     
     */
    public Numberformat getNumberformat() {
        return numberformat;
    }

    /**
     * Sets the value of the numberformat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Numberformat }
     *     
     */
    public void setNumberformat(Numberformat value) {
        this.numberformat = value;
    }

    /**
     * Gets the value of the columnnamesformat property.
     * 
     * @return
     *     possible object is
     *     {@link Columnnamesformat }
     *     
     */
    public Columnnamesformat getColumnnamesformat() {
        return columnnamesformat;
    }

    /**
     * Sets the value of the columnnamesformat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Columnnamesformat }
     *     
     */
    public void setColumnnamesformat(Columnnamesformat value) {
        this.columnnamesformat = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the code property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Code }
     * 
     * 
     */
    public List<Code> getCode() {
        if (code == null) {
            code = new ArrayList<Code>();
        }
        return this.code;
    }

    /**
     * Gets the value of the twistieimage property.
     * 
     * @return
     *     possible object is
     *     {@link Twistieimage }
     *     
     */
    public Twistieimage getTwistieimage() {
        return twistieimage;
    }

    /**
     * Sets the value of the twistieimage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Twistieimage }
     *     
     */
    public void setTwistieimage(Twistieimage value) {
        this.twistieimage = value;
    }

    /**
     * Gets the value of the align property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleAligns }
     *     
     */
    public SimpleAligns getAlign() {
        if (align == null) {
            return SimpleAligns.LEFT;
        } else {
            return align;
        }
    }

    /**
     * Sets the value of the align property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleAligns }
     *     
     */
    public void setAlign(SimpleAligns value) {
        this.align = value;
    }

    /**
     * Gets the value of the showasicons property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isShowasicons() {
        if (showasicons == null) {
            return false;
        } else {
            return showasicons;
        }
    }

    /**
     * Sets the value of the showasicons property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowasicons(Boolean value) {
        this.showasicons = value;
    }

    /**
     * Gets the value of the resizable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isResizable() {
        if (resizable == null) {
            return true;
        } else {
            return resizable;
        }
    }

    /**
     * Sets the value of the resizable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setResizable(Boolean value) {
        this.resizable = value;
    }

    /**
     * Gets the value of the responsesonly property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isResponsesonly() {
        if (responsesonly == null) {
            return false;
        } else {
            return responsesonly;
        }
    }

    /**
     * Sets the value of the responsesonly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setResponsesonly(Boolean value) {
        this.responsesonly = value;
    }

    /**
     * Gets the value of the hidden property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isHidden() {
        if (hidden == null) {
            return false;
        } else {
            return hidden;
        }
    }

    /**
     * Sets the value of the hidden property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHidden(Boolean value) {
        this.hidden = value;
    }

    /**
     * Gets the value of the editable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isEditable() {
        if (editable == null) {
            return false;
        } else {
            return editable;
        }
    }

    /**
     * Sets the value of the editable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEditable(Boolean value) {
        this.editable = value;
    }

    /**
     * Gets the value of the twisties property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isTwisties() {
        if (twisties == null) {
            return false;
        } else {
            return twisties;
        }
    }

    /**
     * Sets the value of the twisties property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTwisties(Boolean value) {
        this.twisties = value;
    }

    /**
     * Gets the value of the sort property.
     * 
     * @return
     *     possible object is
     *     {@link SortOrders }
     *     
     */
    public SortOrders getSort() {
        return sort;
    }

    /**
     * Sets the value of the sort property.
     * 
     * @param value
     *     allowed object is
     *     {@link SortOrders }
     *     
     */
    public void setSort(SortOrders value) {
        this.sort = value;
    }

    /**
     * Gets the value of the sortnocase property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSortnocase() {
        return sortnocase;
    }

    /**
     * Sets the value of the sortnocase property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSortnocase(Boolean value) {
        this.sortnocase = value;
    }

    /**
     * Gets the value of the sortnoaccent property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSortnoaccent() {
        return sortnoaccent;
    }

    /**
     * Sets the value of the sortnoaccent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSortnoaccent(Boolean value) {
        this.sortnoaccent = value;
    }

    /**
     * Gets the value of the separatemultiplevalues property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isSeparatemultiplevalues() {
        if (separatemultiplevalues == null) {
            return false;
        } else {
            return separatemultiplevalues;
        }
    }

    /**
     * Sets the value of the separatemultiplevalues property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSeparatemultiplevalues(Boolean value) {
        this.separatemultiplevalues = value;
    }

    /**
     * Gets the value of the categorized property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isCategorized() {
        if (categorized == null) {
            return false;
        } else {
            return categorized;
        }
    }

    /**
     * Sets the value of the categorized property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCategorized(Boolean value) {
        this.categorized = value;
    }

    /**
     * Gets the value of the resort property.
     * 
     * @return
     *     possible object is
     *     {@link ResortOptions }
     *     
     */
    public ResortOptions getResort() {
        return resort;
    }

    /**
     * Sets the value of the resort property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResortOptions }
     *     
     */
    public void setResort(ResortOptions value) {
        this.resort = value;
    }

    /**
     * Gets the value of the resorttoview property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResorttoview() {
        return resorttoview;
    }

    /**
     * Sets the value of the resorttoview property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResorttoview(String value) {
        this.resorttoview = value;
    }

    /**
     * Gets the value of the resort2 property.
     * 
     * @return
     *     possible object is
     *     {@link SortOrders }
     *     
     */
    public SortOrders getResort2() {
        return resort2;
    }

    /**
     * Sets the value of the resort2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SortOrders }
     *     
     */
    public void setResort2(SortOrders value) {
        this.resort2 = value;
    }

    /**
     * Gets the value of the resort2Column property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getResort2Column() {
        return resort2Column;
    }

    /**
     * Sets the value of the resort2Column property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setResort2Column(BigInteger value) {
        this.resort2Column = value;
    }

    /**
     * Gets the value of the totals property.
     * 
     * @return
     *     possible object is
     *     {@link TotalsOptions }
     *     
     */
    public TotalsOptions getTotals() {
        return totals;
    }

    /**
     * Sets the value of the totals property.
     * 
     * @param value
     *     allowed object is
     *     {@link TotalsOptions }
     *     
     */
    public void setTotals(TotalsOptions value) {
        this.totals = value;
    }

    /**
     * Gets the value of the hidedetailrows property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHidedetailrows() {
        return hidedetailrows;
    }

    /**
     * Sets the value of the hidedetailrows property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHidedetailrows(Boolean value) {
        this.hidedetailrows = value;
    }

    /**
     * Gets the value of the showaslinks property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowaslinks() {
        return showaslinks;
    }

    /**
     * Sets the value of the showaslinks property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowaslinks(Boolean value) {
        this.showaslinks = value;
    }

    /**
     * Gets the value of the itemname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemname() {
        return itemname;
    }

    /**
     * Sets the value of the itemname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemname(String value) {
        this.itemname = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setWidth(Float value) {
        this.width = value;
    }

    /**
     * Gets the value of the listseparator property.
     * 
     * @return
     *     possible object is
     *     {@link ListSeparators }
     *     
     */
    public ListSeparators getListseparator() {
        return listseparator;
    }

    /**
     * Sets the value of the listseparator property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListSeparators }
     *     
     */
    public void setListseparator(ListSeparators value) {
        this.listseparator = value;
    }

    /**
     * Gets the value of the flatinr5 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFlatinr5() {
        return flatinr5;
    }

    /**
     * Sets the value of the flatinr5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFlatinr5(Boolean value) {
        this.flatinr5 = value;
    }

    /**
     * Gets the value of the showascolor property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isShowascolor() {
        if (showascolor == null) {
            return false;
        } else {
            return showascolor;
        }
    }

    /**
     * Sets the value of the showascolor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowascolor(Boolean value) {
        this.showascolor = value;
    }

    /**
     * Gets the value of the userdefinable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isUserdefinable() {
        if (userdefinable == null) {
            return false;
        } else {
            return userdefinable;
        }
    }

    /**
     * Sets the value of the userdefinable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUserdefinable(Boolean value) {
        this.userdefinable = value;
    }

    /**
     * Gets the value of the profiledocname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfiledocname() {
        return profiledocname;
    }

    /**
     * Sets the value of the profiledocname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfiledocname(String value) {
        this.profiledocname = value;
    }

    /**
     * Gets the value of the usecolumnformula property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUsecolumnformula() {
        return usecolumnformula;
    }

    /**
     * Sets the value of the usecolumnformula property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUsecolumnformula(Boolean value) {
        this.usecolumnformula = value;
    }

    /**
     * Gets the value of the hidecolumntitle property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isHidecolumntitle() {
        if (hidecolumntitle == null) {
            return false;
        } else {
            return hidecolumntitle;
        }
    }

    /**
     * Sets the value of the hidecolumntitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHidecolumntitle(Boolean value) {
        this.hidecolumntitle = value;
    }

    /**
     * Gets the value of the hideinr5 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isHideinr5() {
        if (hideinr5 == null) {
            return false;
        } else {
            return hideinr5;
        }
    }

    /**
     * Sets the value of the hideinr5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHideinr5(Boolean value) {
        this.hideinr5 = value;
    }

    /**
     * Gets the value of the deferindexcreation property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isDeferindexcreation() {
        if (deferindexcreation == null) {
            return false;
        } else {
            return deferindexcreation;
        }
    }

    /**
     * Sets the value of the deferindexcreation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDeferindexcreation(Boolean value) {
        this.deferindexcreation = value;
    }

    /**
     * Gets the value of the extwindowwidth property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isExtwindowwidth() {
        if (extwindowwidth == null) {
            return false;
        } else {
            return extwindowwidth;
        }
    }

    /**
     * Sets the value of the extwindowwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExtwindowwidth(Boolean value) {
        this.extwindowwidth = value;
    }

    /**
     * Gets the value of the justifysecondrow property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isJustifysecondrow() {
        if (justifysecondrow == null) {
            return false;
        } else {
            return justifysecondrow;
        }
    }

    /**
     * Sets the value of the justifysecondrow property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setJustifysecondrow(Boolean value) {
        this.justifysecondrow = value;
    }

    /**
     * Gets the value of the viewisnarrow property.
     * 
     * @return
     *     possible object is
     *     {@link NarrowOptions }
     *     
     */
    public NarrowOptions getViewisnarrow() {
        if (viewisnarrow == null) {
            return NarrowOptions.TOP;
        } else {
            return viewisnarrow;
        }
    }

    /**
     * Sets the value of the viewisnarrow property.
     * 
     * @param value
     *     allowed object is
     *     {@link NarrowOptions }
     *     
     */
    public void setViewisnarrow(NarrowOptions value) {
        this.viewisnarrow = value;
    }

    /**
     * Gets the value of the sequence property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSequence() {
        return sequence;
    }

    /**
     * Sets the value of the sequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSequence(BigInteger value) {
        this.sequence = value;
    }

    /**
     * Gets the value of the tileviewer property.
     * 
     * @return
     *     possible object is
     *     {@link TileviewerOptions }
     *     
     */
    public TileviewerOptions getTileviewer() {
        if (tileviewer == null) {
            return TileviewerOptions.TOP;
        } else {
            return tileviewer;
        }
    }

    /**
     * Sets the value of the tileviewer property.
     * 
     * @param value
     *     allowed object is
     *     {@link TileviewerOptions }
     *     
     */
    public void setTileviewer(TileviewerOptions value) {
        this.tileviewer = value;
    }

    /**
     * Gets the value of the linenumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLinenumber() {
        if (linenumber == null) {
            return new BigInteger("1");
        } else {
            return linenumber;
        }
    }

    /**
     * Sets the value of the linenumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLinenumber(BigInteger value) {
        this.linenumber = value;
    }

    /**
     * Gets the value of the extattrs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtattrs() {
        return extattrs;
    }

    /**
     * Sets the value of the extattrs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtattrs(String value) {
        this.extattrs = value;
    }

    /**
     * Gets the value of the publish property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublish() {
        return publish;
    }

    /**
     * Sets the value of the publish property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublish(String value) {
        this.publish = value;
    }

    /**
     * Gets the value of the formatdatatype property.
     * 
     * @return
     *     possible object is
     *     {@link ColumnformatDatatypes }
     *     
     */
    public ColumnformatDatatypes getFormatdatatype() {
        return formatdatatype;
    }

    /**
     * Sets the value of the formatdatatype property.
     * 
     * @param value
     *     allowed object is
     *     {@link ColumnformatDatatypes }
     *     
     */
    public void setFormatdatatype(ColumnformatDatatypes value) {
        this.formatdatatype = value;
    }

    /**
     * Gets the value of the readingorder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReadingorder() {
        if (readingorder == null) {
            return "lefttoright";
        } else {
            return readingorder;
        }
    }

    /**
     * Sets the value of the readingorder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReadingorder(String value) {
        this.readingorder = value;
    }

}
