//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 02:06:11 PM CET 
//


package org.openntf.base.jaxb.dxl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for control complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="control">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eoutlinebackground" type="{http://www.lotus.com/dxl}eoutlinebackground" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "control", namespace = "http://www.lotus.com/dxl", propOrder = {
    "eoutlinebackground"
})
public class Control {

    protected Eoutlinebackground eoutlinebackground;

    /**
     * Gets the value of the eoutlinebackground property.
     * 
     * @return
     *     possible object is
     *     {@link Eoutlinebackground }
     *     
     */
    public Eoutlinebackground getEoutlinebackground() {
        return eoutlinebackground;
    }

    /**
     * Sets the value of the eoutlinebackground property.
     * 
     * @param value
     *     allowed object is
     *     {@link Eoutlinebackground }
     *     
     */
    public void setEoutlinebackground(Eoutlinebackground value) {
        this.eoutlinebackground = value;
    }

}
