//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 02:06:11 PM CET 
//


package org.openntf.base.jaxb.dxl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for datetimeformat.yearformat.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="datetimeformat.yearformat">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="twodigityear"/>
 *     &lt;enumeration value="fourdigityear"/>
 *     &lt;enumeration value="oneletterepochnameonedigityear"/>
 *     &lt;enumeration value="oneletterepochnametwodigityear"/>
 *     &lt;enumeration value="shortepochnameonedigityear"/>
 *     &lt;enumeration value="shortepochnametwodigityear"/>
 *     &lt;enumeration value="fullepochnameonedigityear"/>
 *     &lt;enumeration value="fullepochnametwodigityear"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "datetimeformat.yearformat", namespace = "http://www.lotus.com/dxl")
@XmlEnum
public enum DatetimeformatYearformat {

    @XmlEnumValue("twodigityear")
    TWODIGITYEAR("twodigityear"),
    @XmlEnumValue("fourdigityear")
    FOURDIGITYEAR("fourdigityear"),
    @XmlEnumValue("oneletterepochnameonedigityear")
    ONELETTEREPOCHNAMEONEDIGITYEAR("oneletterepochnameonedigityear"),
    @XmlEnumValue("oneletterepochnametwodigityear")
    ONELETTEREPOCHNAMETWODIGITYEAR("oneletterepochnametwodigityear"),
    @XmlEnumValue("shortepochnameonedigityear")
    SHORTEPOCHNAMEONEDIGITYEAR("shortepochnameonedigityear"),
    @XmlEnumValue("shortepochnametwodigityear")
    SHORTEPOCHNAMETWODIGITYEAR("shortepochnametwodigityear"),
    @XmlEnumValue("fullepochnameonedigityear")
    FULLEPOCHNAMEONEDIGITYEAR("fullepochnameonedigityear"),
    @XmlEnumValue("fullepochnametwodigityear")
    FULLEPOCHNAMETWODIGITYEAR("fullepochnametwodigityear");
    private final String value;

    DatetimeformatYearformat(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DatetimeformatYearformat fromValue(String v) {
        for (DatetimeformatYearformat c: DatetimeformatYearformat.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
