//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 02:06:11 PM CET 
//


package org.openntf.base.jaxb.dxl;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for db2accessviewentry complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="db2accessviewentry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="fieldname" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="notestype" use="required" type="{http://www.lotus.com/dxl}notes.types" />
 *       &lt;attribute name="db2type" use="required" type="{http://www.lotus.com/dxl}db2.types" />
 *       &lt;attribute name="db2index" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="allowtruncation" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="multiplevalue" type="{http://www.lotus.com/dxl}multiplevalue.types" />
 *       &lt;attribute name="db2delimiter" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="db2columnlength" type="{http://www.w3.org/2001/XMLSchema}integer" default="100" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "db2accessviewentry", namespace = "http://www.lotus.com/dxl")
public class Db2Accessviewentry {

    @XmlAttribute(required = true)
    protected String fieldname;
    @XmlAttribute(required = true)
    protected NotesTypes notestype;
    @XmlAttribute(name = "db2type", required = true)
    protected Db2Types db2Type;
    @XmlAttribute(name = "db2index")
    protected Boolean db2Index;
    @XmlAttribute
    protected Boolean allowtruncation;
    @XmlAttribute
    protected MultiplevalueTypes multiplevalue;
    @XmlAttribute(name = "db2delimiter")
    protected String db2Delimiter;
    @XmlAttribute(name = "db2columnlength")
    protected BigInteger db2Columnlength;

    /**
     * Gets the value of the fieldname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldname() {
        return fieldname;
    }

    /**
     * Sets the value of the fieldname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldname(String value) {
        this.fieldname = value;
    }

    /**
     * Gets the value of the notestype property.
     * 
     * @return
     *     possible object is
     *     {@link NotesTypes }
     *     
     */
    public NotesTypes getNotestype() {
        return notestype;
    }

    /**
     * Sets the value of the notestype property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotesTypes }
     *     
     */
    public void setNotestype(NotesTypes value) {
        this.notestype = value;
    }

    /**
     * Gets the value of the db2Type property.
     * 
     * @return
     *     possible object is
     *     {@link Db2Types }
     *     
     */
    public Db2Types getDb2Type() {
        return db2Type;
    }

    /**
     * Sets the value of the db2Type property.
     * 
     * @param value
     *     allowed object is
     *     {@link Db2Types }
     *     
     */
    public void setDb2Type(Db2Types value) {
        this.db2Type = value;
    }

    /**
     * Gets the value of the db2Index property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isDb2Index() {
        if (db2Index == null) {
            return false;
        } else {
            return db2Index;
        }
    }

    /**
     * Sets the value of the db2Index property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDb2Index(Boolean value) {
        this.db2Index = value;
    }

    /**
     * Gets the value of the allowtruncation property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAllowtruncation() {
        if (allowtruncation == null) {
            return false;
        } else {
            return allowtruncation;
        }
    }

    /**
     * Sets the value of the allowtruncation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowtruncation(Boolean value) {
        this.allowtruncation = value;
    }

    /**
     * Gets the value of the multiplevalue property.
     * 
     * @return
     *     possible object is
     *     {@link MultiplevalueTypes }
     *     
     */
    public MultiplevalueTypes getMultiplevalue() {
        return multiplevalue;
    }

    /**
     * Sets the value of the multiplevalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiplevalueTypes }
     *     
     */
    public void setMultiplevalue(MultiplevalueTypes value) {
        this.multiplevalue = value;
    }

    /**
     * Gets the value of the db2Delimiter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDb2Delimiter() {
        return db2Delimiter;
    }

    /**
     * Sets the value of the db2Delimiter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDb2Delimiter(String value) {
        this.db2Delimiter = value;
    }

    /**
     * Gets the value of the db2Columnlength property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDb2Columnlength() {
        if (db2Columnlength == null) {
            return new BigInteger("100");
        } else {
            return db2Columnlength;
        }
    }

    /**
     * Sets the value of the db2Columnlength property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDb2Columnlength(BigInteger value) {
        this.db2Columnlength = value;
    }

}
