//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 02:06:11 PM CET 
//


package org.openntf.base.jaxb.dxl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for embeddeddatepicker complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="embeddeddatepicker">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="font" type="{http://www.lotus.com/dxl}font" minOccurs="0"/>
 *         &lt;element name="border" type="{http://www.lotus.com/dxl}border" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="headerbgcolor" type="{http://www.w3.org/2001/XMLSchema}string" default="none" />
 *       &lt;attribute name="controlbgcolor" type="{http://www.w3.org/2001/XMLSchema}string" default="none" />
 *       &lt;attribute name="textcolor" type="{http://www.w3.org/2001/XMLSchema}string" default="black" />
 *       &lt;attribute name="targetframe" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="proportional" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="heighttype" type="{http://www.lotus.com/dxl}embedded.fit.types" default="fixed" />
 *       &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="widthtype" type="{http://www.lotus.com/dxl}embedded.fit.types" default="fixed" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "embeddeddatepicker", namespace = "http://www.lotus.com/dxl", propOrder = {
    "font",
    "border"
})
public class Embeddeddatepicker {

    protected Font font;
    protected Border border;
    @XmlAttribute
    protected String headerbgcolor;
    @XmlAttribute
    protected String controlbgcolor;
    @XmlAttribute
    protected String textcolor;
    @XmlAttribute
    protected String targetframe;
    @XmlAttribute
    protected Boolean proportional;
    @XmlAttribute
    protected String height;
    @XmlAttribute
    protected EmbeddedFitTypes heighttype;
    @XmlAttribute
    protected String width;
    @XmlAttribute
    protected EmbeddedFitTypes widthtype;

    /**
     * Gets the value of the font property.
     * 
     * @return
     *     possible object is
     *     {@link Font }
     *     
     */
    public Font getFont() {
        return font;
    }

    /**
     * Sets the value of the font property.
     * 
     * @param value
     *     allowed object is
     *     {@link Font }
     *     
     */
    public void setFont(Font value) {
        this.font = value;
    }

    /**
     * Gets the value of the border property.
     * 
     * @return
     *     possible object is
     *     {@link Border }
     *     
     */
    public Border getBorder() {
        return border;
    }

    /**
     * Sets the value of the border property.
     * 
     * @param value
     *     allowed object is
     *     {@link Border }
     *     
     */
    public void setBorder(Border value) {
        this.border = value;
    }

    /**
     * Gets the value of the headerbgcolor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeaderbgcolor() {
        if (headerbgcolor == null) {
            return "none";
        } else {
            return headerbgcolor;
        }
    }

    /**
     * Sets the value of the headerbgcolor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeaderbgcolor(String value) {
        this.headerbgcolor = value;
    }

    /**
     * Gets the value of the controlbgcolor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getControlbgcolor() {
        if (controlbgcolor == null) {
            return "none";
        } else {
            return controlbgcolor;
        }
    }

    /**
     * Sets the value of the controlbgcolor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setControlbgcolor(String value) {
        this.controlbgcolor = value;
    }

    /**
     * Gets the value of the textcolor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextcolor() {
        if (textcolor == null) {
            return "black";
        } else {
            return textcolor;
        }
    }

    /**
     * Sets the value of the textcolor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextcolor(String value) {
        this.textcolor = value;
    }

    /**
     * Gets the value of the targetframe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetframe() {
        return targetframe;
    }

    /**
     * Sets the value of the targetframe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetframe(String value) {
        this.targetframe = value;
    }

    /**
     * Gets the value of the proportional property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isProportional() {
        if (proportional == null) {
            return false;
        } else {
            return proportional;
        }
    }

    /**
     * Sets the value of the proportional property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setProportional(Boolean value) {
        this.proportional = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeight(String value) {
        this.height = value;
    }

    /**
     * Gets the value of the heighttype property.
     * 
     * @return
     *     possible object is
     *     {@link EmbeddedFitTypes }
     *     
     */
    public EmbeddedFitTypes getHeighttype() {
        if (heighttype == null) {
            return EmbeddedFitTypes.FIXED;
        } else {
            return heighttype;
        }
    }

    /**
     * Sets the value of the heighttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmbeddedFitTypes }
     *     
     */
    public void setHeighttype(EmbeddedFitTypes value) {
        this.heighttype = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidth(String value) {
        this.width = value;
    }

    /**
     * Gets the value of the widthtype property.
     * 
     * @return
     *     possible object is
     *     {@link EmbeddedFitTypes }
     *     
     */
    public EmbeddedFitTypes getWidthtype() {
        if (widthtype == null) {
            return EmbeddedFitTypes.FIXED;
        } else {
            return widthtype;
        }
    }

    /**
     * Sets the value of the widthtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmbeddedFitTypes }
     *     
     */
    public void setWidthtype(EmbeddedFitTypes value) {
        this.widthtype = value;
    }

}
