//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 02:06:11 PM CET 
//


package org.openntf.base.jaxb.dxl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for file.encoding.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="file.encoding">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="none"/>
 *     &lt;enumeration value="base64"/>
 *     &lt;enumeration value="quotedprintable"/>
 *     &lt;enumeration value="uuencode"/>
 *     &lt;enumeration value="unknown"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "file.encoding", namespace = "http://www.lotus.com/dxl")
@XmlEnum
public enum FileEncoding {

    @XmlEnumValue("none")
    NONE("none"),
    @XmlEnumValue("base64")
    BASE_64("base64"),
    @XmlEnumValue("quotedprintable")
    QUOTEDPRINTABLE("quotedprintable"),
    @XmlEnumValue("uuencode")
    UUENCODE("uuencode"),
    @XmlEnumValue("unknown")
    UNKNOWN("unknown");
    private final String value;

    FileEncoding(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FileEncoding fromValue(String v) {
        for (FileEncoding c: FileEncoding.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
