//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 02:06:11 PM CET 
//


package org.openntf.base.jaxb.dxl;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for noteinfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="noteinfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="created" type="{http://www.lotus.com/dxl}created" minOccurs="0"/>
 *         &lt;element name="modified" type="{http://www.lotus.com/dxl}modified" minOccurs="0"/>
 *         &lt;element name="revised" type="{http://www.lotus.com/dxl}revised" minOccurs="0"/>
 *         &lt;element name="lastaccessed" type="{http://www.lotus.com/dxl}lastaccessed" minOccurs="0"/>
 *         &lt;element name="addedtofile" type="{http://www.lotus.com/dxl}addedtofile" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="noteid" type="{http://www.lotus.com/dxl}noteshex" />
 *       &lt;attribute name="unid" type="{http://www.lotus.com/dxl}unidhex" />
 *       &lt;attribute name="sequence" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "noteinfo", namespace = "http://www.lotus.com/dxl", propOrder = {
    "created",
    "modified",
    "revised",
    "lastaccessed",
    "addedtofile"
})
public class Noteinfo {

    protected Created created;
    protected Modified modified;
    protected Revised revised;
    protected Lastaccessed lastaccessed;
    protected Addedtofile addedtofile;
    @XmlAttribute
    protected String noteid;
    @XmlAttribute
    protected String unid;
    @XmlAttribute
    protected BigInteger sequence;

    /**
     * Gets the value of the created property.
     * 
     * @return
     *     possible object is
     *     {@link Created }
     *     
     */
    public Created getCreated() {
        return created;
    }

    /**
     * Sets the value of the created property.
     * 
     * @param value
     *     allowed object is
     *     {@link Created }
     *     
     */
    public void setCreated(Created value) {
        this.created = value;
    }

    /**
     * Gets the value of the modified property.
     * 
     * @return
     *     possible object is
     *     {@link Modified }
     *     
     */
    public Modified getModified() {
        return modified;
    }

    /**
     * Sets the value of the modified property.
     * 
     * @param value
     *     allowed object is
     *     {@link Modified }
     *     
     */
    public void setModified(Modified value) {
        this.modified = value;
    }

    /**
     * Gets the value of the revised property.
     * 
     * @return
     *     possible object is
     *     {@link Revised }
     *     
     */
    public Revised getRevised() {
        return revised;
    }

    /**
     * Sets the value of the revised property.
     * 
     * @param value
     *     allowed object is
     *     {@link Revised }
     *     
     */
    public void setRevised(Revised value) {
        this.revised = value;
    }

    /**
     * Gets the value of the lastaccessed property.
     * 
     * @return
     *     possible object is
     *     {@link Lastaccessed }
     *     
     */
    public Lastaccessed getLastaccessed() {
        return lastaccessed;
    }

    /**
     * Sets the value of the lastaccessed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Lastaccessed }
     *     
     */
    public void setLastaccessed(Lastaccessed value) {
        this.lastaccessed = value;
    }

    /**
     * Gets the value of the addedtofile property.
     * 
     * @return
     *     possible object is
     *     {@link Addedtofile }
     *     
     */
    public Addedtofile getAddedtofile() {
        return addedtofile;
    }

    /**
     * Sets the value of the addedtofile property.
     * 
     * @param value
     *     allowed object is
     *     {@link Addedtofile }
     *     
     */
    public void setAddedtofile(Addedtofile value) {
        this.addedtofile = value;
    }

    /**
     * Gets the value of the noteid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoteid() {
        return noteid;
    }

    /**
     * Sets the value of the noteid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoteid(String value) {
        this.noteid = value;
    }

    /**
     * Gets the value of the unid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnid() {
        return unid;
    }

    /**
     * Sets the value of the unid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnid(String value) {
        this.unid = value;
    }

    /**
     * Gets the value of the sequence property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSequence() {
        return sequence;
    }

    /**
     * Sets the value of the sequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSequence(BigInteger value) {
        this.sequence = value;
    }

}
