//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 02:06:11 PM CET 
//


package org.openntf.base.jaxb.dxl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for notes.types.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="notes.types">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="text"/>
 *     &lt;enumeration value="textlist"/>
 *     &lt;enumeration value="time"/>
 *     &lt;enumeration value="number"/>
 *     &lt;enumeration value="timerange"/>
 *     &lt;enumeration value="numberrange"/>
 *     &lt;enumeration value="userdata"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "notes.types", namespace = "http://www.lotus.com/dxl")
@XmlEnum
public enum NotesTypes {

    @XmlEnumValue("text")
    TEXT("text"),
    @XmlEnumValue("textlist")
    TEXTLIST("textlist"),
    @XmlEnumValue("time")
    TIME("time"),
    @XmlEnumValue("number")
    NUMBER("number"),
    @XmlEnumValue("timerange")
    TIMERANGE("timerange"),
    @XmlEnumValue("numberrange")
    NUMBERRANGE("numberrange"),
    @XmlEnumValue("userdata")
    USERDATA("userdata");
    private final String value;

    NotesTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static NotesTypes fromValue(String v) {
        for (NotesTypes c: NotesTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
