//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 02:06:11 PM CET 
//


package org.openntf.base.jaxb.dxl;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for numberformat complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="numberformat">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="digits" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="format" type="{http://www.lotus.com/dxl}numberformat.formats" />
 *       &lt;attribute name="punctuated" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="parens" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="percent" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="bytes" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="varying" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="preference" type="{http://www.lotus.com/dxl}numberformat.preferences" default="usersetting" />
 *       &lt;attribute name="decimalsym" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="thousandssep" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="currencysymtype" type="{http://www.lotus.com/dxl}numberformat.currencysymtypes" />
 *       &lt;attribute name="currencysym" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="usecustomsym" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isocountry" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="symfollows" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="usespaces" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="legacy" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "numberformat", namespace = "http://www.lotus.com/dxl")
public class Numberformat {

    @XmlAttribute
    protected String digits;
    @XmlAttribute
    protected NumberformatFormats format;
    @XmlAttribute
    protected Boolean punctuated;
    @XmlAttribute
    protected Boolean parens;
    @XmlAttribute
    protected Boolean percent;
    @XmlAttribute
    protected Boolean bytes;
    @XmlAttribute
    protected Boolean varying;
    @XmlAttribute
    protected NumberformatPreferences preference;
    @XmlAttribute
    protected String decimalsym;
    @XmlAttribute
    protected String thousandssep;
    @XmlAttribute
    protected NumberformatCurrencysymtypes currencysymtype;
    @XmlAttribute
    protected String currencysym;
    @XmlAttribute
    protected Boolean usecustomsym;
    @XmlAttribute
    protected BigInteger isocountry;
    @XmlAttribute
    protected Boolean symfollows;
    @XmlAttribute
    protected Boolean usespaces;
    @XmlAttribute
    protected Boolean legacy;

    /**
     * Gets the value of the digits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDigits() {
        return digits;
    }

    /**
     * Sets the value of the digits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDigits(String value) {
        this.digits = value;
    }

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link NumberformatFormats }
     *     
     */
    public NumberformatFormats getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberformatFormats }
     *     
     */
    public void setFormat(NumberformatFormats value) {
        this.format = value;
    }

    /**
     * Gets the value of the punctuated property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPunctuated() {
        return punctuated;
    }

    /**
     * Sets the value of the punctuated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPunctuated(Boolean value) {
        this.punctuated = value;
    }

    /**
     * Gets the value of the parens property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isParens() {
        return parens;
    }

    /**
     * Sets the value of the parens property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setParens(Boolean value) {
        this.parens = value;
    }

    /**
     * Gets the value of the percent property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPercent() {
        return percent;
    }

    /**
     * Sets the value of the percent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPercent(Boolean value) {
        this.percent = value;
    }

    /**
     * Gets the value of the bytes property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBytes() {
        return bytes;
    }

    /**
     * Sets the value of the bytes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBytes(Boolean value) {
        this.bytes = value;
    }

    /**
     * Gets the value of the varying property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVarying() {
        return varying;
    }

    /**
     * Sets the value of the varying property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVarying(Boolean value) {
        this.varying = value;
    }

    /**
     * Gets the value of the preference property.
     * 
     * @return
     *     possible object is
     *     {@link NumberformatPreferences }
     *     
     */
    public NumberformatPreferences getPreference() {
        if (preference == null) {
            return NumberformatPreferences.USERSETTING;
        } else {
            return preference;
        }
    }

    /**
     * Sets the value of the preference property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberformatPreferences }
     *     
     */
    public void setPreference(NumberformatPreferences value) {
        this.preference = value;
    }

    /**
     * Gets the value of the decimalsym property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDecimalsym() {
        return decimalsym;
    }

    /**
     * Sets the value of the decimalsym property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecimalsym(String value) {
        this.decimalsym = value;
    }

    /**
     * Gets the value of the thousandssep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThousandssep() {
        return thousandssep;
    }

    /**
     * Sets the value of the thousandssep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThousandssep(String value) {
        this.thousandssep = value;
    }

    /**
     * Gets the value of the currencysymtype property.
     * 
     * @return
     *     possible object is
     *     {@link NumberformatCurrencysymtypes }
     *     
     */
    public NumberformatCurrencysymtypes getCurrencysymtype() {
        return currencysymtype;
    }

    /**
     * Sets the value of the currencysymtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberformatCurrencysymtypes }
     *     
     */
    public void setCurrencysymtype(NumberformatCurrencysymtypes value) {
        this.currencysymtype = value;
    }

    /**
     * Gets the value of the currencysym property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencysym() {
        return currencysym;
    }

    /**
     * Sets the value of the currencysym property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencysym(String value) {
        this.currencysym = value;
    }

    /**
     * Gets the value of the usecustomsym property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUsecustomsym() {
        return usecustomsym;
    }

    /**
     * Sets the value of the usecustomsym property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUsecustomsym(Boolean value) {
        this.usecustomsym = value;
    }

    /**
     * Gets the value of the isocountry property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIsocountry() {
        return isocountry;
    }

    /**
     * Sets the value of the isocountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIsocountry(BigInteger value) {
        this.isocountry = value;
    }

    /**
     * Gets the value of the symfollows property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSymfollows() {
        return symfollows;
    }

    /**
     * Sets the value of the symfollows property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSymfollows(Boolean value) {
        this.symfollows = value;
    }

    /**
     * Gets the value of the usespaces property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUsespaces() {
        return usespaces;
    }

    /**
     * Sets the value of the usespaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUsespaces(Boolean value) {
        this.usespaces = value;
    }

    /**
     * Gets the value of the legacy property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLegacy() {
        return legacy;
    }

    /**
     * Sets the value of the legacy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLegacy(Boolean value) {
        this.legacy = value;
    }

}
