//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 02:06:11 PM CET 
//


package org.openntf.base.jaxb.dxl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for objectref.storage.formats.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="objectref.storage.formats">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="structstorage"/>
 *     &lt;enumeration value="istorageistream"/>
 *     &lt;enumeration value="structstream"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "objectref.storage.formats", namespace = "http://www.lotus.com/dxl")
@XmlEnum
public enum ObjectrefStorageFormats {

    @XmlEnumValue("structstorage")
    STRUCTSTORAGE("structstorage"),
    @XmlEnumValue("istorageistream")
    ISTORAGEISTREAM("istorageistream"),
    @XmlEnumValue("structstream")
    STRUCTSTREAM("structstream");
    private final String value;

    ObjectrefStorageFormats(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ObjectrefStorageFormats fromValue(String v) {
        for (ObjectrefStorageFormats c: ObjectrefStorageFormats.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
