//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 02:06:11 PM CET 
//


package org.openntf.base.jaxb.dxl;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for outlineentry complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="outlineentry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="imageref" type="{http://www.lotus.com/dxl}imageref" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="doclink" type="{http://www.lotus.com/dxl}doclink"/>
 *           &lt;element name="databaselink" type="{http://www.lotus.com/dxl}databaselink"/>
 *           &lt;element name="viewlink" type="{http://www.lotus.com/dxl}viewlink"/>
 *           &lt;element name="namedelementlink" type="{http://www.lotus.com/dxl}namedelementlink"/>
 *           &lt;element name="urllink" type="{http://www.lotus.com/dxl}urllink"/>
 *         &lt;/choice>
 *         &lt;element name="code" type="{http://www.lotus.com/dxl}code" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.lotus.com/dxl}reading.order.attrs"/>
 *       &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="alias" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="popup" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" type="{http://www.lotus.com/dxl}outlineentry.types" />
 *       &lt;attribute name="targetframe" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="displayimage" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="keepfocus" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="hide" type="{http://www.lotus.com/dxl}outlineentry.hidewhen.token" />
 *       &lt;attribute name="level" type="{http://www.w3.org/2001/XMLSchema}integer" default="0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "outlineentry", namespace = "http://www.lotus.com/dxl", propOrder = {
    "imageref",
    "doclink",
    "databaselink",
    "viewlink",
    "namedelementlink",
    "urllink",
    "code"
})
public class Outlineentry {

    protected Imageref imageref;
    protected Doclink doclink;
    protected Databaselink databaselink;
    protected Viewlink viewlink;
    protected Namedelementlink namedelementlink;
    protected Urllink urllink;
    protected List<Code> code;
    @XmlAttribute
    protected String label;
    @XmlAttribute
    protected String alias;
    @XmlAttribute
    protected String popup;
    @XmlAttribute
    protected OutlineentryTypes type;
    @XmlAttribute
    protected String targetframe;
    @XmlAttribute
    protected Boolean displayimage;
    @XmlAttribute
    protected Boolean keepfocus;
    @XmlAttribute
    protected List<OutlineentryHidewhenTokens> hide;
    @XmlAttribute
    protected BigInteger level;
    @XmlAttribute
    protected String readingorder;

    /**
     * Gets the value of the imageref property.
     * 
     * @return
     *     possible object is
     *     {@link Imageref }
     *     
     */
    public Imageref getImageref() {
        return imageref;
    }

    /**
     * Sets the value of the imageref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Imageref }
     *     
     */
    public void setImageref(Imageref value) {
        this.imageref = value;
    }

    /**
     * Gets the value of the doclink property.
     * 
     * @return
     *     possible object is
     *     {@link Doclink }
     *     
     */
    public Doclink getDoclink() {
        return doclink;
    }

    /**
     * Sets the value of the doclink property.
     * 
     * @param value
     *     allowed object is
     *     {@link Doclink }
     *     
     */
    public void setDoclink(Doclink value) {
        this.doclink = value;
    }

    /**
     * Gets the value of the databaselink property.
     * 
     * @return
     *     possible object is
     *     {@link Databaselink }
     *     
     */
    public Databaselink getDatabaselink() {
        return databaselink;
    }

    /**
     * Sets the value of the databaselink property.
     * 
     * @param value
     *     allowed object is
     *     {@link Databaselink }
     *     
     */
    public void setDatabaselink(Databaselink value) {
        this.databaselink = value;
    }

    /**
     * Gets the value of the viewlink property.
     * 
     * @return
     *     possible object is
     *     {@link Viewlink }
     *     
     */
    public Viewlink getViewlink() {
        return viewlink;
    }

    /**
     * Sets the value of the viewlink property.
     * 
     * @param value
     *     allowed object is
     *     {@link Viewlink }
     *     
     */
    public void setViewlink(Viewlink value) {
        this.viewlink = value;
    }

    /**
     * Gets the value of the namedelementlink property.
     * 
     * @return
     *     possible object is
     *     {@link Namedelementlink }
     *     
     */
    public Namedelementlink getNamedelementlink() {
        return namedelementlink;
    }

    /**
     * Sets the value of the namedelementlink property.
     * 
     * @param value
     *     allowed object is
     *     {@link Namedelementlink }
     *     
     */
    public void setNamedelementlink(Namedelementlink value) {
        this.namedelementlink = value;
    }

    /**
     * Gets the value of the urllink property.
     * 
     * @return
     *     possible object is
     *     {@link Urllink }
     *     
     */
    public Urllink getUrllink() {
        return urllink;
    }

    /**
     * Sets the value of the urllink property.
     * 
     * @param value
     *     allowed object is
     *     {@link Urllink }
     *     
     */
    public void setUrllink(Urllink value) {
        this.urllink = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the code property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Code }
     * 
     * 
     */
    public List<Code> getCode() {
        if (code == null) {
            code = new ArrayList<Code>();
        }
        return this.code;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the alias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlias() {
        return alias;
    }

    /**
     * Sets the value of the alias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlias(String value) {
        this.alias = value;
    }

    /**
     * Gets the value of the popup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPopup() {
        return popup;
    }

    /**
     * Sets the value of the popup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPopup(String value) {
        this.popup = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link OutlineentryTypes }
     *     
     */
    public OutlineentryTypes getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutlineentryTypes }
     *     
     */
    public void setType(OutlineentryTypes value) {
        this.type = value;
    }

    /**
     * Gets the value of the targetframe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetframe() {
        return targetframe;
    }

    /**
     * Sets the value of the targetframe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetframe(String value) {
        this.targetframe = value;
    }

    /**
     * Gets the value of the displayimage property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isDisplayimage() {
        if (displayimage == null) {
            return true;
        } else {
            return displayimage;
        }
    }

    /**
     * Sets the value of the displayimage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDisplayimage(Boolean value) {
        this.displayimage = value;
    }

    /**
     * Gets the value of the keepfocus property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isKeepfocus() {
        if (keepfocus == null) {
            return false;
        } else {
            return keepfocus;
        }
    }

    /**
     * Sets the value of the keepfocus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setKeepfocus(Boolean value) {
        this.keepfocus = value;
    }

    /**
     * Gets the value of the hide property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hide property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHide().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OutlineentryHidewhenTokens }
     * 
     * 
     */
    public List<OutlineentryHidewhenTokens> getHide() {
        if (hide == null) {
            hide = new ArrayList<OutlineentryHidewhenTokens>();
        }
        return this.hide;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLevel() {
        if (level == null) {
            return new BigInteger("0");
        } else {
            return level;
        }
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLevel(BigInteger value) {
        this.level = value;
    }

    /**
     * Gets the value of the readingorder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReadingorder() {
        if (readingorder == null) {
            return "lefttoright";
        } else {
            return readingorder;
        }
    }

    /**
     * Sets the value of the readingorder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReadingorder(String value) {
        this.readingorder = value;
    }

}
