//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 02:06:11 PM CET 
//


package org.openntf.base.jaxb.dxl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for pardef complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pardef">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="code" type="{http://www.lotus.com/dxl}code" minOccurs="0"/>
 *         &lt;element name="parstyle" type="{http://www.lotus.com/dxl}parstyle" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.lotus.com/dxl}reading.order.attrs"/>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="align" type="{http://www.lotus.com/dxl}pardef.aligns" default="left" />
 *       &lt;attribute name="linespacing" type="{http://www.lotus.com/dxl}pardef.linespacings" default="1" />
 *       &lt;attribute name="spacebefore" type="{http://www.lotus.com/dxl}pardef.linespacings" default="1" />
 *       &lt;attribute name="spaceafter" type="{http://www.lotus.com/dxl}pardef.linespacings" default="1" />
 *       &lt;attribute name="leftmargin" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="rightmargin" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="firstlineleftmargin" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tabs" type="{http://www.w3.org/2001/XMLSchema}token" />
 *       &lt;attribute name="hide" type="{http://www.lotus.com/dxl}pardef.hide.token" default="" />
 *       &lt;attribute name="newpage" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="keepwithnext" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="keeptogether" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="list" type="{http://www.lotus.com/dxl}pardef.list.styles" default="none" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pardef", namespace = "http://www.lotus.com/dxl", propOrder = {
    "code",
    "parstyle"
})
public class Pardef {

    protected Code code;
    protected Parstyle parstyle;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String id;
    @XmlAttribute
    protected PardefAligns align;
    @XmlAttribute
    protected String linespacing;
    @XmlAttribute
    protected String spacebefore;
    @XmlAttribute
    protected String spaceafter;
    @XmlAttribute
    protected String leftmargin;
    @XmlAttribute
    protected String rightmargin;
    @XmlAttribute
    protected String firstlineleftmargin;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String tabs;
    @XmlAttribute
    protected List<PardefHideTokens> hide;
    @XmlAttribute
    protected Boolean newpage;
    @XmlAttribute
    protected Boolean keepwithnext;
    @XmlAttribute
    protected Boolean keeptogether;
    @XmlAttribute
    protected PardefListStyles list;
    @XmlAttribute
    protected String readingorder;

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link Code }
     *     
     */
    public Code getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link Code }
     *     
     */
    public void setCode(Code value) {
        this.code = value;
    }

    /**
     * Gets the value of the parstyle property.
     * 
     * @return
     *     possible object is
     *     {@link Parstyle }
     *     
     */
    public Parstyle getParstyle() {
        return parstyle;
    }

    /**
     * Sets the value of the parstyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Parstyle }
     *     
     */
    public void setParstyle(Parstyle value) {
        this.parstyle = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the align property.
     * 
     * @return
     *     possible object is
     *     {@link PardefAligns }
     *     
     */
    public PardefAligns getAlign() {
        if (align == null) {
            return PardefAligns.LEFT;
        } else {
            return align;
        }
    }

    /**
     * Sets the value of the align property.
     * 
     * @param value
     *     allowed object is
     *     {@link PardefAligns }
     *     
     */
    public void setAlign(PardefAligns value) {
        this.align = value;
    }

    /**
     * Gets the value of the linespacing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinespacing() {
        if (linespacing == null) {
            return "1";
        } else {
            return linespacing;
        }
    }

    /**
     * Sets the value of the linespacing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinespacing(String value) {
        this.linespacing = value;
    }

    /**
     * Gets the value of the spacebefore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpacebefore() {
        if (spacebefore == null) {
            return "1";
        } else {
            return spacebefore;
        }
    }

    /**
     * Sets the value of the spacebefore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpacebefore(String value) {
        this.spacebefore = value;
    }

    /**
     * Gets the value of the spaceafter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpaceafter() {
        if (spaceafter == null) {
            return "1";
        } else {
            return spaceafter;
        }
    }

    /**
     * Sets the value of the spaceafter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpaceafter(String value) {
        this.spaceafter = value;
    }

    /**
     * Gets the value of the leftmargin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeftmargin() {
        return leftmargin;
    }

    /**
     * Sets the value of the leftmargin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeftmargin(String value) {
        this.leftmargin = value;
    }

    /**
     * Gets the value of the rightmargin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRightmargin() {
        return rightmargin;
    }

    /**
     * Sets the value of the rightmargin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRightmargin(String value) {
        this.rightmargin = value;
    }

    /**
     * Gets the value of the firstlineleftmargin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstlineleftmargin() {
        return firstlineleftmargin;
    }

    /**
     * Sets the value of the firstlineleftmargin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstlineleftmargin(String value) {
        this.firstlineleftmargin = value;
    }

    /**
     * Gets the value of the tabs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTabs() {
        return tabs;
    }

    /**
     * Sets the value of the tabs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTabs(String value) {
        this.tabs = value;
    }

    /**
     * Gets the value of the hide property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hide property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHide().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PardefHideTokens }
     * 
     * 
     */
    public List<PardefHideTokens> getHide() {
        if (hide == null) {
            hide = new ArrayList<PardefHideTokens>();
        }
        return this.hide;
    }

    /**
     * Gets the value of the newpage property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isNewpage() {
        if (newpage == null) {
            return false;
        } else {
            return newpage;
        }
    }

    /**
     * Sets the value of the newpage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNewpage(Boolean value) {
        this.newpage = value;
    }

    /**
     * Gets the value of the keepwithnext property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isKeepwithnext() {
        return keepwithnext;
    }

    /**
     * Sets the value of the keepwithnext property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setKeepwithnext(Boolean value) {
        this.keepwithnext = value;
    }

    /**
     * Gets the value of the keeptogether property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isKeeptogether() {
        return keeptogether;
    }

    /**
     * Sets the value of the keeptogether property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setKeeptogether(Boolean value) {
        this.keeptogether = value;
    }

    /**
     * Gets the value of the list property.
     * 
     * @return
     *     possible object is
     *     {@link PardefListStyles }
     *     
     */
    public PardefListStyles getList() {
        if (list == null) {
            return PardefListStyles.NONE;
        } else {
            return list;
        }
    }

    /**
     * Sets the value of the list property.
     * 
     * @param value
     *     allowed object is
     *     {@link PardefListStyles }
     *     
     */
    public void setList(PardefListStyles value) {
        this.list = value;
    }

    /**
     * Gets the value of the readingorder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReadingorder() {
        if (readingorder == null) {
            return "lefttoright";
        } else {
            return readingorder;
        }
    }

    /**
     * Sets the value of the readingorder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReadingorder(String value) {
        this.readingorder = value;
    }

}
