//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 02:06:11 PM CET 
//


package org.openntf.base.jaxb.dxl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for richtext complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="richtext">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;group ref="{http://www.lotus.com/dxl}richtext.block"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "richtext", namespace = "http://www.lotus.com/dxl", propOrder = {
    "parOrPardefOrTable"
})
public class Richtext {

    @XmlElements({
        @XmlElement(name = "section", type = Section.class),
        @XmlElement(name = "subformref", type = Subformref.class),
        @XmlElement(name = "table", type = Table.class),
        @XmlElement(name = "pardef", type = Pardef.class),
        @XmlElement(name = "compositedata", type = Compositedata.class),
        @XmlElement(name = "par", type = Par.class),
        @XmlElement(name = "formregionend", type = Formregionend.class),
        @XmlElement(name = "formregionbegin", type = Formregionbegin.class),
        @XmlElement(name = "block", type = Block.class)
    })
    protected List<java.lang.Object> parOrPardefOrTable;

    /**
     * Gets the value of the parOrPardefOrTable property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parOrPardefOrTable property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParOrPardefOrTable().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Section }
     * {@link Subformref }
     * {@link Table }
     * {@link Pardef }
     * {@link Compositedata }
     * {@link Par }
     * {@link Formregionend }
     * {@link Formregionbegin }
     * {@link Block }
     * 
     * 
     */
    public List<java.lang.Object> getParOrPardefOrTable() {
        if (parOrPardefOrTable == null) {
            parOrPardefOrTable = new ArrayList<java.lang.Object>();
        }
        return this.parOrPardefOrTable;
    }

}
