//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 02:06:11 PM CET 
//


package org.openntf.base.jaxb.dxl;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for schedule complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="schedule">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="starttime" type="{http://www.lotus.com/dxl}starttime" minOccurs="0"/>
 *         &lt;element name="endtime" type="{http://www.lotus.com/dxl}endtime" minOccurs="0"/>
 *         &lt;element name="startdate" type="{http://www.lotus.com/dxl}startdate" minOccurs="0"/>
 *         &lt;element name="enddate" type="{http://www.lotus.com/dxl}enddate" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" use="required" type="{http://www.lotus.com/dxl}schedule.types" />
 *       &lt;attribute name="hours" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="minutes" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="onweekends" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="runlocation" type="{http://www.lotus.com/dxl}schedule.runlocations" />
 *       &lt;attribute name="runserver" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="dayofweek" type="{http://www.lotus.com/dxl}day.names" />
 *       &lt;attribute name="dateinmonth" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "schedule", namespace = "http://www.lotus.com/dxl", propOrder = {
    "starttime",
    "endtime",
    "startdate",
    "enddate"
})
public class Schedule {

    protected Starttime starttime;
    protected Endtime endtime;
    protected Startdate startdate;
    protected Enddate enddate;
    @XmlAttribute(required = true)
    protected ScheduleTypes type;
    @XmlAttribute
    protected BigInteger hours;
    @XmlAttribute
    protected BigInteger minutes;
    @XmlAttribute
    protected Boolean onweekends;
    @XmlAttribute
    protected ScheduleRunlocations runlocation;
    @XmlAttribute
    protected String runserver;
    @XmlAttribute
    protected DayNames dayofweek;
    @XmlAttribute
    protected BigInteger dateinmonth;

    /**
     * Gets the value of the starttime property.
     * 
     * @return
     *     possible object is
     *     {@link Starttime }
     *     
     */
    public Starttime getStarttime() {
        return starttime;
    }

    /**
     * Sets the value of the starttime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Starttime }
     *     
     */
    public void setStarttime(Starttime value) {
        this.starttime = value;
    }

    /**
     * Gets the value of the endtime property.
     * 
     * @return
     *     possible object is
     *     {@link Endtime }
     *     
     */
    public Endtime getEndtime() {
        return endtime;
    }

    /**
     * Sets the value of the endtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Endtime }
     *     
     */
    public void setEndtime(Endtime value) {
        this.endtime = value;
    }

    /**
     * Gets the value of the startdate property.
     * 
     * @return
     *     possible object is
     *     {@link Startdate }
     *     
     */
    public Startdate getStartdate() {
        return startdate;
    }

    /**
     * Sets the value of the startdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Startdate }
     *     
     */
    public void setStartdate(Startdate value) {
        this.startdate = value;
    }

    /**
     * Gets the value of the enddate property.
     * 
     * @return
     *     possible object is
     *     {@link Enddate }
     *     
     */
    public Enddate getEnddate() {
        return enddate;
    }

    /**
     * Sets the value of the enddate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Enddate }
     *     
     */
    public void setEnddate(Enddate value) {
        this.enddate = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleTypes }
     *     
     */
    public ScheduleTypes getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleTypes }
     *     
     */
    public void setType(ScheduleTypes value) {
        this.type = value;
    }

    /**
     * Gets the value of the hours property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHours() {
        return hours;
    }

    /**
     * Sets the value of the hours property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHours(BigInteger value) {
        this.hours = value;
    }

    /**
     * Gets the value of the minutes property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMinutes() {
        return minutes;
    }

    /**
     * Sets the value of the minutes property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMinutes(BigInteger value) {
        this.minutes = value;
    }

    /**
     * Gets the value of the onweekends property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isOnweekends() {
        if (onweekends == null) {
            return true;
        } else {
            return onweekends;
        }
    }

    /**
     * Sets the value of the onweekends property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOnweekends(Boolean value) {
        this.onweekends = value;
    }

    /**
     * Gets the value of the runlocation property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleRunlocations }
     *     
     */
    public ScheduleRunlocations getRunlocation() {
        return runlocation;
    }

    /**
     * Sets the value of the runlocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleRunlocations }
     *     
     */
    public void setRunlocation(ScheduleRunlocations value) {
        this.runlocation = value;
    }

    /**
     * Gets the value of the runserver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRunserver() {
        return runserver;
    }

    /**
     * Sets the value of the runserver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRunserver(String value) {
        this.runserver = value;
    }

    /**
     * Gets the value of the dayofweek property.
     * 
     * @return
     *     possible object is
     *     {@link DayNames }
     *     
     */
    public DayNames getDayofweek() {
        return dayofweek;
    }

    /**
     * Sets the value of the dayofweek property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayNames }
     *     
     */
    public void setDayofweek(DayNames value) {
        this.dayofweek = value;
    }

    /**
     * Gets the value of the dateinmonth property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDateinmonth() {
        return dateinmonth;
    }

    /**
     * Sets the value of the dateinmonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDateinmonth(BigInteger value) {
        this.dateinmonth = value;
    }

}
