//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 02:06:11 PM CET 
//


package org.openntf.base.jaxb.dxl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for schedule.runlocations.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="schedule.runlocations">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="local"/>
 *     &lt;enumeration value="any"/>
 *     &lt;enumeration value="choose"/>
 *     &lt;enumeration value="server"/>
 *     &lt;enumeration value="specific"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "schedule.runlocations", namespace = "http://www.lotus.com/dxl")
@XmlEnum
public enum ScheduleRunlocations {

    @XmlEnumValue("local")
    LOCAL("local"),
    @XmlEnumValue("any")
    ANY("any"),
    @XmlEnumValue("choose")
    CHOOSE("choose"),
    @XmlEnumValue("server")
    SERVER("server"),
    @XmlEnumValue("specific")
    SPECIFIC("specific");
    private final String value;

    ScheduleRunlocations(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ScheduleRunlocations fromValue(String v) {
        for (ScheduleRunlocations c: ScheduleRunlocations.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
