//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 02:06:11 PM CET 
//


package org.openntf.base.jaxb.dxl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for search complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="search">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="datechoice" type="{http://www.lotus.com/dxl}datechoice"/>
 *         &lt;element name="formchoice" type="{http://www.lotus.com/dxl}formchoice"/>
 *         &lt;element name="formfieldschoice" type="{http://www.lotus.com/dxl}formfieldschoice"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="word" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/choice>
 *       &lt;attribute name="type" use="required" type="{http://www.lotus.com/dxl}search.types" />
 *       &lt;attribute name="folder" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="field" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="contains" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="all" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "search", namespace = "http://www.lotus.com/dxl", propOrder = {
    "datechoiceOrFormchoiceOrFormfieldschoice"
})
public class Search {

    @XmlElementRefs({
        @XmlElementRef(name = "datechoice", namespace = "http://www.lotus.com/dxl", type = JAXBElement.class),
        @XmlElementRef(name = "formchoice", namespace = "http://www.lotus.com/dxl", type = JAXBElement.class),
        @XmlElementRef(name = "word", namespace = "http://www.lotus.com/dxl", type = JAXBElement.class),
        @XmlElementRef(name = "name", namespace = "http://www.lotus.com/dxl", type = JAXBElement.class),
        @XmlElementRef(name = "formfieldschoice", namespace = "http://www.lotus.com/dxl", type = JAXBElement.class)
    })
    protected List<JAXBElement<?>> datechoiceOrFormchoiceOrFormfieldschoice;
    @XmlAttribute(required = true)
    protected SearchTypes type;
    @XmlAttribute
    protected String folder;
    @XmlAttribute
    protected String field;
    @XmlAttribute
    protected Boolean contains;
    @XmlAttribute
    protected String value;
    @XmlAttribute
    protected Boolean all;

    /**
     * Gets the value of the datechoiceOrFormchoiceOrFormfieldschoice property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the datechoiceOrFormchoiceOrFormfieldschoice property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDatechoiceOrFormchoiceOrFormfieldschoice().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Datechoice }{@code >}
     * {@link JAXBElement }{@code <}{@link Formchoice }{@code >}
     * {@link JAXBElement }{@code <}{@link Formfieldschoice }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getDatechoiceOrFormchoiceOrFormfieldschoice() {
        if (datechoiceOrFormchoiceOrFormfieldschoice == null) {
            datechoiceOrFormchoiceOrFormfieldschoice = new ArrayList<JAXBElement<?>>();
        }
        return this.datechoiceOrFormchoiceOrFormfieldschoice;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link SearchTypes }
     *     
     */
    public SearchTypes getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchTypes }
     *     
     */
    public void setType(SearchTypes value) {
        this.type = value;
    }

    /**
     * Gets the value of the folder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFolder() {
        return folder;
    }

    /**
     * Sets the value of the folder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFolder(String value) {
        this.folder = value;
    }

    /**
     * Gets the value of the field property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField() {
        return field;
    }

    /**
     * Sets the value of the field property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField(String value) {
        this.field = value;
    }

    /**
     * Gets the value of the contains property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isContains() {
        return contains;
    }

    /**
     * Sets the value of the contains property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setContains(Boolean value) {
        this.contains = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the all property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAll() {
        return all;
    }

    /**
     * Sets the value of the all property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAll(Boolean value) {
        this.all = value;
    }

}
