//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 02:06:11 PM CET 
//


package org.openntf.base.jaxb.dxl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for search.types.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="search.types">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="byauthor"/>
 *     &lt;enumeration value="bydate"/>
 *     &lt;enumeration value="byfield"/>
 *     &lt;enumeration value="byformnames"/>
 *     &lt;enumeration value="byform"/>
 *     &lt;enumeration value="infolder"/>
 *     &lt;enumeration value="multiplewords"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "search.types", namespace = "http://www.lotus.com/dxl")
@XmlEnum
public enum SearchTypes {

    @XmlEnumValue("byauthor")
    BYAUTHOR("byauthor"),
    @XmlEnumValue("bydate")
    BYDATE("bydate"),
    @XmlEnumValue("byfield")
    BYFIELD("byfield"),
    @XmlEnumValue("byformnames")
    BYFORMNAMES("byformnames"),
    @XmlEnumValue("byform")
    BYFORM("byform"),
    @XmlEnumValue("infolder")
    INFOLDER("infolder"),
    @XmlEnumValue("multiplewords")
    MULTIPLEWORDS("multiplewords");
    private final String value;

    SearchTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SearchTypes fromValue(String v) {
        for (SearchTypes c: SearchTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
