//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 02:06:11 PM CET 
//


package org.openntf.base.jaxb.dxl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for section.border.styles.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="section.border.styles">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="none"/>
 *     &lt;enumeration value="single"/>
 *     &lt;enumeration value="double"/>
 *     &lt;enumeration value="triple"/>
 *     &lt;enumeration value="shadow"/>
 *     &lt;enumeration value="twoline"/>
 *     &lt;enumeration value="windowcaption"/>
 *     &lt;enumeration value="gradient"/>
 *     &lt;enumeration value="tab"/>
 *     &lt;enumeration value="tabdiag"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "section.border.styles", namespace = "http://www.lotus.com/dxl")
@XmlEnum
public enum SectionBorderStyles {

    @XmlEnumValue("none")
    NONE("none"),
    @XmlEnumValue("single")
    SINGLE("single"),
    @XmlEnumValue("double")
    DOUBLE("double"),
    @XmlEnumValue("triple")
    TRIPLE("triple"),
    @XmlEnumValue("shadow")
    SHADOW("shadow"),
    @XmlEnumValue("twoline")
    TWOLINE("twoline"),
    @XmlEnumValue("windowcaption")
    WINDOWCAPTION("windowcaption"),
    @XmlEnumValue("gradient")
    GRADIENT("gradient"),
    @XmlEnumValue("tab")
    TAB("tab"),
    @XmlEnumValue("tabdiag")
    TABDIAG("tabdiag");
    private final String value;

    SectionBorderStyles(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SectionBorderStyles fromValue(String v) {
        for (SectionBorderStyles c: SectionBorderStyles.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
