//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 02:06:11 PM CET 
//


package org.openntf.base.jaxb.dxl;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for sectiontitle complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sectiontitle">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="font" type="{http://www.lotus.com/dxl}font" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="text" type="{http://www.lotus.com/dxl}text"/>
 *           &lt;element name="code" type="{http://www.lotus.com/dxl}code"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="pardef" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="borderstyle" type="{http://www.lotus.com/dxl}section.border.styles" default="none" />
 *       &lt;attribute name="hidewhenexpanded" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="textpropid" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sectiontitle", namespace = "http://www.lotus.com/dxl", propOrder = {
    "font",
    "text",
    "code"
})
public class Sectiontitle {

    protected Font font;
    protected Text text;
    protected Code code;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String pardef;
    @XmlAttribute
    protected String color;
    @XmlAttribute
    protected SectionBorderStyles borderstyle;
    @XmlAttribute
    protected Boolean hidewhenexpanded;
    @XmlAttribute
    protected BigInteger textpropid;

    /**
     * Gets the value of the font property.
     * 
     * @return
     *     possible object is
     *     {@link Font }
     *     
     */
    public Font getFont() {
        return font;
    }

    /**
     * Sets the value of the font property.
     * 
     * @param value
     *     allowed object is
     *     {@link Font }
     *     
     */
    public void setFont(Font value) {
        this.font = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link Text }
     *     
     */
    public Text getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link Text }
     *     
     */
    public void setText(Text value) {
        this.text = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link Code }
     *     
     */
    public Code getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link Code }
     *     
     */
    public void setCode(Code value) {
        this.code = value;
    }

    /**
     * Gets the value of the pardef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPardef() {
        return pardef;
    }

    /**
     * Sets the value of the pardef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPardef(String value) {
        this.pardef = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColor(String value) {
        this.color = value;
    }

    /**
     * Gets the value of the borderstyle property.
     * 
     * @return
     *     possible object is
     *     {@link SectionBorderStyles }
     *     
     */
    public SectionBorderStyles getBorderstyle() {
        if (borderstyle == null) {
            return SectionBorderStyles.NONE;
        } else {
            return borderstyle;
        }
    }

    /**
     * Sets the value of the borderstyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link SectionBorderStyles }
     *     
     */
    public void setBorderstyle(SectionBorderStyles value) {
        this.borderstyle = value;
    }

    /**
     * Gets the value of the hidewhenexpanded property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isHidewhenexpanded() {
        if (hidewhenexpanded == null) {
            return false;
        } else {
            return hidewhenexpanded;
        }
    }

    /**
     * Sets the value of the hidewhenexpanded property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHidewhenexpanded(Boolean value) {
        this.hidewhenexpanded = value;
    }

    /**
     * Gets the value of the textpropid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTextpropid() {
        return textpropid;
    }

    /**
     * Sets the value of the textpropid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTextpropid(BigInteger value) {
        this.textpropid = value;
    }

}
