//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 02:06:11 PM CET 
//


package org.openntf.base.jaxb.dxl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for simpleaction.types.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="simpleaction.types">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="copytodatabase"/>
 *     &lt;enumeration value="copytofolder"/>
 *     &lt;enumeration value="delete"/>
 *     &lt;enumeration value="markread"/>
 *     &lt;enumeration value="markunread"/>
 *     &lt;enumeration value="modifyfield"/>
 *     &lt;enumeration value="modifybyform"/>
 *     &lt;enumeration value="movetofolder"/>
 *     &lt;enumeration value="removefromfolder"/>
 *     &lt;enumeration value="sendreply"/>
 *     &lt;enumeration value="runagent"/>
 *     &lt;enumeration value="send"/>
 *     &lt;enumeration value="sendmail"/>
 *     &lt;enumeration value="sendnewsletter"/>
 *     &lt;enumeration value="runformula"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "simpleaction.types", namespace = "http://www.lotus.com/dxl")
@XmlEnum
public enum SimpleactionTypes {

    @XmlEnumValue("copytodatabase")
    COPYTODATABASE("copytodatabase"),
    @XmlEnumValue("copytofolder")
    COPYTOFOLDER("copytofolder"),
    @XmlEnumValue("delete")
    DELETE("delete"),
    @XmlEnumValue("markread")
    MARKREAD("markread"),
    @XmlEnumValue("markunread")
    MARKUNREAD("markunread"),
    @XmlEnumValue("modifyfield")
    MODIFYFIELD("modifyfield"),
    @XmlEnumValue("modifybyform")
    MODIFYBYFORM("modifybyform"),
    @XmlEnumValue("movetofolder")
    MOVETOFOLDER("movetofolder"),
    @XmlEnumValue("removefromfolder")
    REMOVEFROMFOLDER("removefromfolder"),
    @XmlEnumValue("sendreply")
    SENDREPLY("sendreply"),
    @XmlEnumValue("runagent")
    RUNAGENT("runagent"),
    @XmlEnumValue("send")
    SEND("send"),
    @XmlEnumValue("sendmail")
    SENDMAIL("sendmail"),
    @XmlEnumValue("sendnewsletter")
    SENDNEWSLETTER("sendnewsletter"),
    @XmlEnumValue("runformula")
    RUNFORMULA("runformula");
    private final String value;

    SimpleactionTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SimpleactionTypes fromValue(String v) {
        for (SimpleactionTypes c: SimpleactionTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
