//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 02:06:11 PM CET 
//


package org.openntf.base.jaxb.dxl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for size.types.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="size.types">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="pixels"/>
 *     &lt;enumeration value="inches"/>
 *     &lt;enumeration value="ems"/>
 *     &lt;enumeration value="exs"/>
 *     &lt;enumeration value="percent"/>
 *     &lt;enumeration value="characters"/>
 *     &lt;enumeration value="auto"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "size.types", namespace = "http://www.lotus.com/dxl")
@XmlEnum
public enum SizeTypes {

    @XmlEnumValue("pixels")
    PIXELS("pixels"),
    @XmlEnumValue("inches")
    INCHES("inches"),
    @XmlEnumValue("ems")
    EMS("ems"),
    @XmlEnumValue("exs")
    EXS("exs"),
    @XmlEnumValue("percent")
    PERCENT("percent"),
    @XmlEnumValue("characters")
    CHARACTERS("characters"),
    @XmlEnumValue("auto")
    AUTO("auto");
    private final String value;

    SizeTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SizeTypes fromValue(String v) {
        for (SizeTypes c: SizeTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
