//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 02:06:11 PM CET 
//


package org.openntf.base.jaxb.dxl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for table.widthtypes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="table.widthtypes">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="fixedleft"/>
 *     &lt;enumeration value="fixedcenter"/>
 *     &lt;enumeration value="fixedright"/>
 *     &lt;enumeration value="fitmargins"/>
 *     &lt;enumeration value="fitwindow"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "table.widthtypes", namespace = "http://www.lotus.com/dxl")
@XmlEnum
public enum TableWidthtypes {

    @XmlEnumValue("fixedleft")
    FIXEDLEFT("fixedleft"),
    @XmlEnumValue("fixedcenter")
    FIXEDCENTER("fixedcenter"),
    @XmlEnumValue("fixedright")
    FIXEDRIGHT("fixedright"),
    @XmlEnumValue("fitmargins")
    FITMARGINS("fitmargins"),
    @XmlEnumValue("fitwindow")
    FITWINDOW("fitwindow");
    private final String value;

    TableWidthtypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TableWidthtypes fromValue(String v) {
        for (TableWidthtypes c: TableWidthtypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
