//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 02:06:11 PM CET 
//


package org.openntf.base.jaxb.dxl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for table.rowdisplays.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="table.rowdisplays">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="all"/>
 *     &lt;enumeration value="tabs"/>
 *     &lt;enumeration value="timer"/>
 *     &lt;enumeration value="onclick"/>
 *     &lt;enumeration value="compute"/>
 *     &lt;enumeration value="tabscompute"/>
 *     &lt;enumeration value="onclicktimer"/>
 *     &lt;enumeration value="onopentimer"/>
 *     &lt;enumeration value="captions"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "table.rowdisplays", namespace = "http://www.lotus.com/dxl")
@XmlEnum
public enum TableRowdisplays {

    @XmlEnumValue("all")
    ALL("all"),
    @XmlEnumValue("tabs")
    TABS("tabs"),
    @XmlEnumValue("timer")
    TIMER("timer"),
    @XmlEnumValue("onclick")
    ONCLICK("onclick"),
    @XmlEnumValue("compute")
    COMPUTE("compute"),
    @XmlEnumValue("tabscompute")
    TABSCOMPUTE("tabscompute"),
    @XmlEnumValue("onclicktimer")
    ONCLICKTIMER("onclicktimer"),
    @XmlEnumValue("onopentimer")
    ONOPENTIMER("onopentimer"),
    @XmlEnumValue("captions")
    CAPTIONS("captions");
    private final String value;

    TableRowdisplays(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TableRowdisplays fromValue(String v) {
        for (TableRowdisplays c: TableRowdisplays.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
